- name: Download dstat
  become: yes
  get_url:
    url: https://github.com/dagwieers/dstat/archive/0.7.3.tar.gz
    dest: /tmp

- name: dstat.tar.bz2
  unarchive:
    src: /tmp/dstat-0.7.2.tar.bz2
    dest: /tmp/dstat-0.7.2
    remote_src: yes

- name: Install dstat
  become: yes
  copy:
    src: /tmp/dstat-0.7.2/dstat
    dest: /usr/bin/dstat
    remote_src: yes
