- name: add new setting
  become: yes
  blockinfile:
    dest: /etc/sysctl.conf
    block: |
      net.ipv4.tcp_max_tw_buckets = 2000000
      net.ipv4.ip_local_port_range = 10000 65000
      net.core.somaxconn = 32768
      net.core.netdev_max_backlog = 8192
      net.ipv4.tcp_tw_reuse = 1
      net.ipv4.tcp_fin_timeout = 10

- name: increase file descriptor
  become: yes
  blockinfile:
    dest: /etc/sysctl.conf
    block: "fs.file-max = 50000"

- name: Enable new sysctl
  become: yes
  command: /sbin/sysctl -p
