- name: get myprofiler
  become: yes
  get_url:
    url: https://github.com/KLab/myprofiler/releases/download/0.1/myprofiler.linux_amd64.tar.gz
    dest: /tmp

- name: add myprofiler directory
  become: yes
  file:
    path: /tmp/myprofiler
    state: directory

- name: unzip myprofiler
  become: yes
  unarchive:
    src: /tmp/myprofiler.linux_amd64.tar.gz
    dest: /tmp/myprofiler
    remote_src: yes

- name: copy myprofiler
  become: yes
  copy:
    src: /tmp/myprofiler/myprofiler
    dest: /usr/bin/myprofiler
    mode: 755
    remote_src: yes
